app/views/add_tracks.py
import urllib.parse
from flask import Blueprint, session, request, jsonify

blueprint = Blueprint('add_tracks', __name__, url_prefix="/add_tracks/")


@blueprint.route("/", methods=["POST"])
def add_tracks():
    # get the data from ajax
    ids = urllib.parse.unquote(request.data.decode("utf-8")).replace("data=",
                                                                     "").split(
        ",+|+,")

    # get all values from the data
    current_track = [ids[0]]
    list_name = ids[1].replace("+", " ")
    current_list = ids[2]
    track_name = session["sp"].track(current_track[0])["name"]

    # if a song has been added in this current session
    if "added" in session.keys():
        # if this song has not yet been added to this playlist, add it
        if not (current_track, current_list) in session["added"]:
            try:
                session["sp"].user_playlist_add_tracks(session["body"]["id"], \
                                                       current_list,
                                                       list(current_track))
            except Exception as e:
                return jsonify({
                                   "error": f"The following error occured: {str(e).split(':')[-1]}"})
            session["added"].append((current_track, current_list))
            return jsonify({"msg": f"Added {track_name} to {list_name}!"})

        # if this song has already been added to this playlist, let the user know
        return jsonify(
            {"error": f"{track_name} has already been added to {list_name}!"})

    # if no songs have been added in the session yet, add the song
    try:
        session["sp"].user_playlist_add_tracks(session["body"]["id"], \
                                               current_list,
                                               list(current_track))
        session["added"] = [(current_track, current_list)]
    except Exception as e:
        return jsonify(
            {"error": f"The following error occured: {str(e).split(':')[-1]}"})
    return jsonify({"msg": f"Added {track_name} to {list_name}!"})

app/views/callback.py
import base64

import requests
import spotipy
from flask import request, render_template, Blueprint, redirect, session

from config import Config

blueprint = Blueprint('callback', __name__, url_prefix="/callback/")

config = Config()


@blueprint.route("/", methods=["GET"])
def callback():
    # encode the client_id and client_secret
    auth = base64.urlsafe_b64encode(f"{config.SPOTIFY_CLIENT_ID}:"
                                    f"{config.SPOTIFY_CLIENT_SECRET}"
                                    .encode("utf-8"))

    # find the callback code provided by spotify and remove unnecessary
    # information
    rule = str(request.full_path)
    # if the user got to this page without a proper redirect, send them
    # to their profile page
    try:
        code = rule.split("?code=")[1].split("&")[0]
    except IndexError:
        return redirect("profile")

    # create a header
    auth_header = {
        'Authorization': 'Basic ' + str(auth, "utf-8")
    }

    # create data
    data = {
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': request.base_url,
        'scope': config.SPOTIFY_SCOPE
    }

    # post the request to the token-generator in spotify's API
    response = requests.post('https://accounts.spotify.com/api/token',
                             headers=auth_header, data=data,
                             verify=True).json()

    # find the user's info based on their token
    session["body"] = requests.get('https://api.spotify.com/v1/me', headers={
        'Authorization': 'Bearer ' + response['access_token']}, verify=True).json()

    session["name"] = session["body"]["display_name"]

    # load API
    session["sp"] = spotipy.Spotify(auth=response['access_token'])
    # Find the current user's playlists
    playlists = session["sp"].current_user_playlists()
    # add the playlist data to the variable

    session['playlists'] = playlists

    # return information to user
    return render_template("index.html", name=session["name"])

app/views/profile.py
from flask import render_template, Blueprint, session, redirect, url_for, \
    flash, request

blueprint = Blueprint('profile', __name__, url_prefix="/profile/")


@blueprint.route("/", methods=["GET", "POST"])
def profile():
    # show the user their name and playlists (this should probably include
    # more relevant stuff, like an image and whatever later)
    if request.method == "GET":
        playlists = []

        for l in session["playlists"]["items"]:
            if l["images"]:
                playlists.append((l["name"], l["id"], l["tracks"]["total"],
                                  l["images"][0]["url"]))
            else:
                playlists.append(
                    (l["name"], l["id"], l["tracks"]["total"], None))

        return render_template("profile.html", name=session['name'],
                               playlists=playlists)

    flash("You are not logged in (anymore)!")
    session.clear()
    return redirect(url_for('home.index'))

app/views/results.py
import random

import SPARQLWrapper as SPARQLWrapper
from flask import render_template, Blueprint, session, redirect, url_for, \
    request

from app.utils.dbpedia import DBpedia

from SPARQLWrapper import SPARQLWrapper, JSON

blueprint = Blueprint('results', __name__, url_prefix="/results/")


@blueprint.route("/", methods=["GET"])
def results():
    # load the query results
    session["query_results"] = DBpedia.query(session["query_local"])

    # Only send name and playlists to html if the user is logged in
    if "name" in session and "playlists" in session:
        return render_template("results.html",
                               name=session["name"],
                               results=session["query_results"],
                               playlists=[(l["name"], l["id"]) for l in
                                          session['playlists']['items']])
    # if the user is not logged in, only send the results to html
    return render_template("results.html", name=None,
                           results=session["query_results"], playlists=None)


@blueprint.route("/advanced/", methods=["POST"])
def advanced_results():
    # find requirements
    genre = request.form["genre"].replace("&", "%26").replace("'",
                                                              "%27").replace(
        " ", "%20")
    # if no genre is provided, query for all genres
    if not genre:
        genre = "Track"
    else:
        genre += "-track"

    # init variables
    danceability_min = request.form['dance-min']
    danceability_max = request.form['dance-max']
    duration_min = request.form['time-min']
    duration_max = request.form['time-max']
    energy_min = request.form['energy-min']
    energy_max = request.form['energy-max']
    instrumentalness_min = request.form['instrumental-min']
    instrumentalness_max = request.form['instrumental-max']
    tempo_min = request.form['tempo-min']
    tempo_max = request.form['tempo-max']
    valence_min = request.form['mood-min']
    valence_max = request.form['mood-max']

    # connect to local repository
    repo = SPARQLWrapper("https://graphdb.yunusdemir.nl/repositories/semusic")
    repo.setQuery(f"""
    PREFIX semu: <http://semusic.com/kad19/>
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    PREFIX dbp: <http://dbpedia.org/property/>
    PREFIX dbo: <http://dbpedia.org/ontology/>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

    select ?id ?artist where {{ 
        ?track a semu:{genre} ;
                foaf:name ?label ;
                semu:hasDanceability ?danceability ;
                semu:hasDuration ?duration ;
                semu:hasEnergy ?energy ;
                semu:hasId ?id ;
                semu:hasInstrumentalness ?instrumentalness ;
                semu:hasTempo ?tempo ;
                semu:hasValence ?valence ;
                semu:hasArtist/foaf:name ?artist .

                FILTER(?danceability >= {danceability_min} && ?danceability <= {danceability_max})
                FILTER(?duration >= {duration_min} && ?duration <= {duration_max})
                FILTER(?energy >= {energy_min} && ?energy <= {energy_max})
                FILTER(?instrumentalness >= {instrumentalness_min} && ?instrumentalness <= {instrumentalness_max})
                FILTER(?tempo >= {tempo_min} && ?tempo <= {tempo_max})
                FILTER(?valence >= {valence_min} && ?valence <= {valence_max})

    }} """)

    repo.setReturnFormat(JSON)
    results = repo.query().convert()
    session["query_local"] = results

    return redirect(url_for("results.results"))


@blueprint.route("/simple/", methods=["POST"])
def simple_results():
    # find requirements
    genre = request.form["genre"].replace("&", "%26").replace("'",
                                                              "%27").replace(
        " ", "%20")
    # if no genre is provided, query for all genres
    if not genre:
        genre = "Track"
    else:
        genre += "-track"

    valence_min = 0
    valence_max = 1

    tempo_min = 0
    tempo_max = 221

    duration_min = 0
    duration_max = 900000

    mood = request.form["moodoptions"]
    tempo = request.form["speedoptions"]
    duration = request.form['durationoptions']

    if mood == 'sad':
        valence_max = 0.35
    elif mood == 'happy':
        valence_min = 0.7

    if tempo == 'slow':
        tempo_max = 76
    elif tempo == 'fast':
        tempo_min = 120

    if duration == 'short':
        duration_max = 180000
    elif duration == 'long':
        duration_min = 240000

    # connect to local repository
    repo = SPARQLWrapper("https://graphdb.yunusdemir.nl/repositories/semusic")
    repo.setQuery(f"""
    PREFIX semu: <http://semusic.com/kad19/>
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    PREFIX dbp: <http://dbpedia.org/property/>
    PREFIX dbo: <http://dbpedia.org/ontology/>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

    select ?id ?artist where {{ 
        ?track a semu:{genre} ;
                foaf:name ?label ;
                semu:hasDanceability ?danceability ;
                semu:hasDuration ?duration ;
                semu:hasEnergy ?energy ;
                semu:hasId ?id ;
                semu:hasInstrumentalness ?instrumentalness ;
                semu:hasTempo ?tempo ;
                semu:hasValence ?valence ;
                semu:hasArtist/foaf:name ?artist .

                FILTER(?duration >= {duration_min} && ?duration <= {duration_max})
                FILTER(?tempo >= {tempo_min} && ?tempo <= {tempo_max})
                FILTER(?valence >= {valence_min} && ?valence <= {valence_max})

    }} """)
    repo.setReturnFormat(JSON)
    results = repo.query().convert()
    session["query_local"] = results

    return redirect(url_for("results.results"))

app/templates/advanced_results.html
{% extends "layout.html" %}

{% block title %}
    Results
{% endblock %}

{% block main %}
    <div class="centered">{{ results }}</div>
{% endblock %}

app/templates/callback.html
{% extends "layout.html" %}

{% block title %}
    Login succesful!
{% endblock %}

{% block main %}
    <div class="centered">Succesfully logged in as user: {{ name }}</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet"/>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="icon" href="{{ url_for('static', filename='favi.ico') }}">

    <title>Semusic: {% block title %}{% endblock %}</title>
</head>
<body>
<nav id="mainmenu" class="navbar navbar-dark bg-dark">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('home.index') }}">Semusic</a>
        </li>
    </ul>
    {% if not name %}
        <form action="{{ url_for('home.index') }}" method="post">
            <button type="submit" class="btn btn-primary btn-login">Connect to Spotify!</button>
        </form>
    {% else %}
        <ul class="nav navbar-nav ml-auto justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('profile.profile') }}">Logged in
                    as: {{ name }}</a>
            </li>
        </ul>
    {% endif %}
</nav>

<main>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    {% block main %}{% endblock %}
</main>

    </body>
</html>

app/templates/profile.html
{% extends "layout.html" %}

{% block title %}
    {{ name }}'s profile
{% endblock %}

{% block main %}
    <div class="align profile">
        <div>
            <h6><b>{{ name }}</b>'s playlists: </h6>
        </div>
        <div>
            <ul class="list-group">
                {% for list in playlists %}
                <li class="list-group-item list-group-item-dark left">
                    {% if list[2] %}
                    <img src="{{ list[3] }}" height="32" width="32">
                    {% endif %}
                    <a href="https://open.spotify.com/playlist/{{ list[1] }}" target="_blank" class="pl-link">{{ list[0] }}</a> ({{ list[2] }} tracks)
                </li>
                {% endfor %}
            </ul>
        </div>
        <form action="{{ url_for('profile.profile') }}" method="post">
            <button type="submit" class="btn btn-primary centered footv2">Logout</button>
        </form>
    </div>
{% endblock %}

app/templates/results.html
{% extends "layout.html" %}

{% block title %}
    Results
{% endblock %}

{% block main %}
    {% if results %}
        <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">Song</th>
            <th scope="col">Artist's discography</th>
            <th scope="col">Artist's years active</th>
            {% if playlists %}
                <th scope="col">Add to a playlist</th>{% endif %}
        </tr>
        </thead>
        <tbody>
        {% for row in results %}
            <tr>
                <td>
                    <iframe src="https://open.spotify.com/embed/track/{{ row.id.value }}"
                            width="300" height="80" frameborder="0" allowtransparency="true"
                            allow="encrypted-media"></iframe>
                </td>
                <td>
                    {% if row.topic.value != "No discography was found" %}
                        <a href="{{ row.topic.value }}#Discography"
                           target="_blank">{{ row.artist.value }}'s discography</a>
                    {% else %}
                        {{ row.topic.value }}
                    {% endif %}
                </td>
                <td>{{ row.started.value }}{% if row.ended.value %} -
                    {{ row.ended.value }}{% endif %}</td>
                {% if playlists %}
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-primary dropdown-toggle" type="button"
                                    id="dropdownMenuButton" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                Playlist
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                {% for list in playlists %}
                                    <a class="dropdown-item" id="playlist" href="#"
                                       name="{{ row.id.value }}, | ,{{ list[0] }}, | ,{{ list[1] }}">{{ list[0] }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </td>
                {% endif %}
            </tr>

        {% endfor %}
        </tbody>
        <a class="btn btn-secondary centered foot" href="{{ url_for('results.results') }}"
        role="button">Refresh results</a>
        </table>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

        <script type=text/javascript>
            $(document).ready(function () {
                var ids;
                $("a#playlist").on("click", function (event) {
                    event.preventDefault()

                    ids = $(this).attr("name");

                    $.ajax({
                        type: 'POST',
                        url: "{{url_for('add_tracks.add_tracks')}}",
                        contentType: 'application/json;charset=UTF-8',
                        data: {'data': ids}
                    }).done(function (data) {
                            if (data.error) {
                                $("#error_msg").text(data.error).fadeIn("fast", function () {
                                    $("#error_msg").delay(2500).fadeOut();
                                });
                                $("#success_msg").hide();
                            } else {
                                $("#success_msg").text(data.msg).fadeIn("fast", function () {
                                    $("#success_msg").delay(2500).fadeOut();
                                });
                                $("#error_msg").hide();
                            }
                        }
                    );
                });
            });
        </script>
        <form>
        </form>

        <div class="pop-up" id="success_msg" style="display:none;"></div>
        <div class="pop-up" id="error_msg" style="display:none;"></div>

    {% else %}
        <div class="no_results">Sorry, no results were found. :( Please try again with different
            requirements!
        </div>
    {% endif %}


{% endblock %}